#!/usr/bin/env python3
"""
Friday VL Search - Searches captions generated by Qwen VL
"""

import sys
import json
import pickle
from pathlib import Path
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss

INDEX_DIR = Path.home() / "friday/index"

def search(query: str, k: int = 5):
    print(f"Searching: '{query}'")

    # Load index
    embed_model = SentenceTransformer('all-MiniLM-L6-v2')
    index = faiss.read_index(str(INDEX_DIR / "vl_text.index"))
    with open(INDEX_DIR / "vl_paths.pkl", "rb") as f:
        paths = pickle.load(f)

    # Load captions for display
    with open(INDEX_DIR / "captions.json", "r") as f:
        captions = json.load(f)

    # Search
    emb = embed_model.encode(query)
    D, I = index.search(np.array([emb]).astype('float32'), k)

    print(f"\nTop {len(I[0])} results:")
    results = []
    for score, idx in zip(D[0], I[0]):
        path = paths[idx]
        cap = captions[path]
        print(f"  {score:.4f} | {Path(path).name}")
        print(f"         {cap[:80]}...")
        results.append(path)
    print()
    return results

if __name__ == "__main__":
    if len(sys.argv) > 1:
        query = " ".join(sys.argv[1:])
    else:
        query = input("Enter search query: ")
    search(query)
